language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.7"

install:
  - "travis_retry pip install -r requirements.txt"
  - "travis_retry pip install -e .[all]"

script: py.test --cov=tika

after_success: coveralls
